Importing Libraries

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.10.0'

# Part 1 - Data Preprocessing

Importing the dataset

In [7]:
dataset = pd.read_csv('ECG_NAGPUR-2.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[[0.40677966 0.4039548  0.40112994 ... 0.71186441 0.70338983 0.69774011]
 [0.71125265 0.70912951 0.71125265 ... 0.91932059 0.92569002 0.92569002]
 [0.43808256 0.43808256 0.43408788 ... 0.39147803 0.38881491 0.38881491]
 ...
 [0.32939189 0.32922297 0.33783784 ... 0.34695946 0.34851351 0.34364865]
 [0.88132417 0.88194878 0.88257339 ... 0.63678951 0.63678326 0.61905059]
 [0.64961569 0.64988073 0.65014577 ... 0.44772595 0.42646965 0.426467  ]]


In [9]:
print(y)

[1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0
 1 1 1 0]


Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 

In [11]:
!pip install scikit-learn

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Building the ANN

Initializing the ANN

In [16]:

ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
7/7 [==============================] - 1s 3ms/step - loss: 0.7514 - accuracy: 0.5952
Epoch 2/100
7/7 [==============================] - 0s 3ms/step - loss: 0.6096 - accuracy: 0.7000
Epoch 3/100
7/7 [==============================] - 0s 5ms/step - loss: 0.5663 - accuracy: 0.7524
Epoch 4/100
7/7 [==============================] - 0s 3ms/step - loss: 0.5442 - accuracy: 0.7619
Epoch 5/100
7/7 [==============================] - 0s 3ms/step - loss: 0.5344 - accuracy: 0.7714
Epoch 6/100
7/7 [==============================] - 0s 4ms/step - loss: 0.5241 - accuracy: 0.7810
Epoch 7/100
7/7 [==============================] - 0s 3ms/step - loss: 0.5163 - accuracy: 0.7667
Epoch 8/100
7/7 [==============================] - 0s 4ms/step - loss: 0.5081 - accuracy: 0.7714
Epoch 9/100
7/7 [==============================] - 0s 4ms/step - loss: 0.5024 - accuracy: 0.7762
Epoch 10/100
7/7 [==============================] - 0s 3ms/step - loss: 0.4926 - accuracy: 0.7857
Epoch 11/100
7/7 [===========

# Part 4 - Making the predictions and evaluating the model

Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 0s/step
[[1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 4  4]
 [10 35]]


0.7358490566037735

In [26]:
import pickle
pickle.dump(ann,open('ECG_Phase2_model_KNN.pkl','wb'))

INFO:tensorflow:Assets written to: ram://b7efc228-36c8-4f51-b168-58fd1d782c57/assets


In [25]:
from flask import Flask, render_template, request
from prediction_utils import *



ModuleNotFoundError: No module named 'flask'

In [38]:
import numpy as np
import pandas as pd

In [39]:
d=pd.read_pickle("ECG_Phase2_model_KNN.pkl")
print(d)

FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ram://00d0592e-e9ed-4f1d-a9e7-5fa3c3428845/variables/variables
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.

In [30]:
df = pd.read_csv('ECG_NAGPUR-2.csv')
print(df)

           C1        C2        C3        C4        C5        C6        C7  \
0    0.406780  0.403955  0.401130  0.401130  0.401130  0.395480  0.395480   
1    0.711253  0.709130  0.711253  0.711253  0.707006  0.707006  0.709130   
2    0.438083  0.438083  0.434088  0.431425  0.434088  0.435419  0.435419   
3    0.916667  0.913462  0.923077  0.929487  0.939103  0.929487  0.919872   
4    0.748691  0.746073  0.738220  0.740838  0.748691  0.746073  0.746073   
..        ...       ...       ...       ...       ...       ...       ...   
258  0.412527  0.410367  0.410151  0.408207  0.403888  0.406048  0.403672   
259  0.260456  0.257605  0.258555  0.258460  0.259506  0.258365  0.253802   
260  0.329392  0.329223  0.337838  0.344595  0.353041  0.363176  0.380068   
261  0.881324  0.881949  0.882573  0.887570  0.888195  0.888819  0.883198   
262  0.649616  0.649881  0.650146  0.639014  0.636364  0.636629  0.623112   

           C8        C9       C10  ...     C4992     C4993     C4994  \
0  

In [31]:
arr = df.to_numpy()
print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[0.40677966 0.4039548  0.40112994 ... 0.70338983 0.69774011 1.        ]
 [0.71125265 0.70912951 0.71125265 ... 0.92569002 0.92569002 1.        ]
 [0.43808256 0.43808256 0.43408788 ... 0.38881491 0.38881491 0.        ]
 ...
 [0.32939189 0.32922297 0.33783784 ... 0.34851351 0.34364865 1.        ]
 [0.88132417 0.88194878 0.88257339 ... 0.63678326 0.61905059 1.        ]
 [0.64961569 0.64988073 0.65014577 ... 0.42646965 0.426467   0.        ]]
<class 'numpy.ndarray'>


In [36]:
import pickle

def storeData():
    # initializing data to be stored in db
    Omkar = {'key' : 'Omkar', 'name' : 'Omkar Pathak',
    'age' : 21, 'pay' : 40000}
    Jagdish = {'key' : 'Jagdish', 'name' : 'Jagdish Pathak',
    'age' : 50, 'pay' : 50000}
  
    # database
    db = {}
    db['Omkar'] = Omkar
    db['Jagdish'] = Jagdish
      
    # Its important to use binary mode
    dbfile = open('examplePickle', 'ab')
      
    # source, destination
    pickle.dump(db, dbfile)                     
    dbfile.close()
  
def loadData():
    # for reading also binary mode is important
    dbfile = open('examplePickle', 'rb')     
    db = pickle.load(dbfile)
    for keys in db:
        print(keys, '=>', db[keys])
    dbfile.close()
  
if __name__ == '__main__':
    storeData()
    loadData()

Omkar => {'key': 'Omkar', 'name': 'Omkar Pathak', 'age': 21, 'pay': 40000}
Jagdish => {'key': 'Jagdish', 'name': 'Jagdish Pathak', 'age': 50, 'pay': 50000}


In [54]:
import pickle
obj = pickle.load(open("ECG_Phase2_model_KNN (1).pickle", "rb"))

FileNotFoundError: [Errno 2] No such file or directory: 'ECG_Phase2_model_KNN (1).pickle'

In [57]:
import pickle
import pprint
obj = pickle.load(open("ECG_Phase2_model_KNN (1).pickle", "rb"))
with open("out.txt", "a") as f:
     pprint.pprint(obj, stream=f)

FileNotFoundError: [Errno 2] No such file or directory: 'ECG_Phase2_model_KNN (1).pickle'

In [52]:
from flask import Flask, render_template, request
from prediction_utils import *

model = pickle.load(open('ECG_Phase2_model_KNN.pkl','rb'))

app = Flask(__name__)
 
    for(0<i<4999)
    v1 = 
    v2 = str(i+1)
    v1 + v2 =key
    
    arr = df.to_numpy()
print('\nNumpy Array\n----------\n', arr)
print(type(arr))

    arr = np.loadtxt("ECG_NAGPUR-2.csv", delimiter=",")
minimum=arr.min()
arr1=arr-minimum
maximum=arr1.max()
arr1=arr1/maximum
arr1.tofile('ECG_NAGPUR-2_normalised.csv', sep = ',')
    






model_prediction = predict()
  return render_template('prediction.html', name=name, -----=f"{model_prediction}%")


app.run(debug=True)

IndentationError: unexpected indent (3393555924.py, line 15)

In [59]:
!pip install flask 

     -------------------------------------- 101.5/101.5 kB 2.9 MB/s eta 0:00:00


In [63]:
from flask import Flask,request,jsonify
import numpy as np
import pandas as pd
import pickle
model = pickle.load(open('ECG_Phase2_model_KNN.pkl','rb'))
app = Flask(_name_)
@app.route('/')
def index():
    return "Hello world"
@app.route('/predict',methods=['GET','POST'])
def predict():
    coordinate = request.form.get('coordinate')
    coordinates=[]
    for i in coordinate.split():
        i=int(i)
        coordinates.append(i)
    arr1 = np.array(coordinates)
    print(arr1)
    minimum = arr1.min()
    prr1 = arr1 - minimum
    maximum = prr1.max()
    prr1 = prr1 / maximum
    result = model.predict([prr1])[0]
    return jsonify({'checking':str(result)})
if _name_ == '_main_':
    app.run(debug=True)

FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ram://41631fdc-0688-4766-8922-b6c65498518c/variables/variables
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.

In [ ]:
from flask import Flask,re